"use client"

import { useEffect, useState } from "react"
import { BadgeDollarSign, Box, CheckCircle2, MapPinned, PackageCheck, Save, Truck } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { DEPARTAMENTOS, formatCOP } from "@/lib/data"
import { calculateShipping, freeShippingProgress, initialShippingSettings, readShippingSettings, SHIPPING_SETTINGS_KEY, SHIPPING_UPDATED_EVENT, type ShippingMethodId, type ShippingSettings } from "@/lib/shipping"

export function ShippingSettingsView() {
  const [settings, setSettings] = useState<ShippingSettings>(initialShippingSettings)
  const [saved, setSaved] = useState(false)
  const [preview, setPreview] = useState({ subtotal: 98000, quantity: 4, department: "Bogotá D.C.", method: "standard" as ShippingMethodId })
  useEffect(() => setSettings(readShippingSettings()), [])

  const quote = calculateShipping(settings, preview)
  const progress = freeShippingProgress(settings, preview.subtotal, preview.quantity)

  function save() {
    localStorage.setItem(SHIPPING_SETTINGS_KEY, JSON.stringify(settings))
    window.dispatchEvent(new Event(SHIPPING_UPDATED_EVENT))
    setSaved(true)
    window.setTimeout(() => setSaved(false), 2500)
  }

  function updateMethod(id: ShippingMethodId, patch: Partial<ShippingSettings[ShippingMethodId]>) {
    setSettings({ ...settings, [id]: { ...settings[id], ...patch } })
  }

  return <div className="space-y-5">
    <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-bold">Envíos</h1><Badge variant="outline">Parametrización mock</Badge></div><p className="mt-1 text-sm text-muted-foreground">Define costos, cobertura, tiempos y condiciones para obtener envío gratis.</p></div><Button onClick={save}><Save className="mr-2 h-4 w-4" />{saved ? "Configuración guardada" : "Guardar cambios"}</Button></div>

    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Summary icon={Truck} label="Servicio" value={settings.enabled ? "Activo" : "Inactivo"} tone="emerald" /><Summary icon={BadgeDollarSign} label="Tarifa estándar" value={`Desde ${formatCOP(settings.standard.baseCost)}`} tone="sky" /><Summary icon={Box} label="Envío gratis" value={freeRuleSummary(settings)} tone="violet" /><Summary icon={MapPinned} label="Zonas activas" value={String(settings.zones.filter((z) => z.active).length)} tone="amber" /></div>

    <div className="grid gap-5 xl:grid-cols-[1fr_380px]">
      <div className="space-y-5">
        <Card><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="font-bold">Condiciones generales</h2><p className="text-xs text-muted-foreground">Estas reglas se aplican de inmediato en producto, carrito y checkout.</p></div><Toggle checked={settings.enabled} onChange={(checked) => setSettings({ ...settings, enabled: checked })} label="Habilitar envíos" /></div><CardContent className="space-y-5 p-5"><div className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-muted/40 p-4"><div><p className="font-semibold">Beneficio de envío gratis</p><p className="text-xs text-muted-foreground">Permite configurar el beneficio por valor, unidades o ambas condiciones.</p></div><Toggle checked={settings.freeShipping.enabled} onChange={(checked) => setSettings({ ...settings, freeShipping: { ...settings.freeShipping, enabled: checked } })} label="Activo" /></div><div className="grid gap-4 md:grid-cols-2"><RuleCard checked={settings.freeShipping.byAmount} onChecked={(checked) => setSettings({ ...settings, freeShipping: { ...settings.freeShipping, byAmount: checked } })} title="Por valor de la compra" description="El subtotal alcanza este monto"><Field label="Monto mínimo"><Input type="number" min="0" step="1000" value={settings.freeShipping.minimumAmount} onChange={(e) => setSettings({ ...settings, freeShipping: { ...settings.freeShipping, minimumAmount: Number(e.target.value) } })} /></Field></RuleCard><RuleCard checked={settings.freeShipping.byQuantity} onChecked={(checked) => setSettings({ ...settings, freeShipping: { ...settings.freeShipping, byQuantity: checked } })} title="Por cantidad de productos" description="La suma de unidades alcanza esta cantidad"><Field label="Unidades mínimas"><Input type="number" min="1" step="1" value={settings.freeShipping.minimumQuantity} onChange={(e) => setSettings({ ...settings, freeShipping: { ...settings.freeShipping, minimumQuantity: Number(e.target.value) } })} /></Field></RuleCard></div>{settings.freeShipping.byAmount && settings.freeShipping.byQuantity && <Field label="Forma de evaluar las condiciones"><Select value={settings.freeShipping.mode} onValueChange={(value) => value && setSettings({ ...settings, freeShipping: { ...settings.freeShipping, mode: value as ShippingSettings["freeShipping"]["mode"] } })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="any">Cumplir cualquiera de las dos</SelectItem><SelectItem value="all">Cumplir valor y cantidad al mismo tiempo</SelectItem></SelectContent></Select></Field>}</CardContent></Card>

        <Card><div className="border-b px-5 py-4"><h2 className="font-bold">Métodos de entrega</h2><p className="text-xs text-muted-foreground">La tarifa de zona se suma al costo base.</p></div><CardContent className="grid gap-4 p-5 md:grid-cols-2"><MethodCard title="Envío estándar" settings={settings.standard} update={(patch) => updateMethod("standard", patch)} /><MethodCard title="Envío express" settings={settings.express} update={(patch) => updateMethod("express", patch)} /></CardContent></Card>

        <Card><div className="border-b px-5 py-4"><h2 className="font-bold">Zonas y recargos</h2><p className="text-xs text-muted-foreground">La zona sin departamentos funciona como cobertura para el resto del país.</p></div><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Zona</TableHead><TableHead>Departamentos incluidos</TableHead><TableHead className="w-44">Recargo</TableHead><TableHead>Estado</TableHead></TableRow></TableHeader><TableBody>{settings.zones.map((zone) => <TableRow key={zone.id}><TableCell className="font-semibold">{zone.name}</TableCell><TableCell className="max-w-md whitespace-normal text-xs text-muted-foreground">{zone.departments.length ? zone.departments.join(", ") : "Todos los demás departamentos"}</TableCell><TableCell><Input aria-label={`Recargo de ${zone.name}`} type="number" min="0" step="1000" value={zone.surcharge} onChange={(e) => setSettings({ ...settings, zones: settings.zones.map((item) => item.id === zone.id ? { ...item, surcharge: Number(e.target.value) } : item) })} /></TableCell><TableCell><Toggle checked={zone.active} onChange={(checked) => setSettings({ ...settings, zones: settings.zones.map((item) => item.id === zone.id ? { ...item, active: checked } : item) })} label={zone.active ? "Activa" : "Inactiva"} /></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
      </div>

      <aside className="space-y-4 xl:sticky xl:top-5 xl:h-fit"><Card className="overflow-hidden border-primary/20"><div className="bg-primary px-5 py-4 text-primary-foreground"><p className="text-xs uppercase tracking-wider text-primary-foreground/70">Simulador</p><h2 className="font-bold">Cotización para el cliente</h2></div><CardContent className="space-y-4 p-5"><Field label="Subtotal"><Input type="number" min="0" step="1000" value={preview.subtotal} onChange={(e) => setPreview({ ...preview, subtotal: Number(e.target.value) })} /></Field><Field label="Cantidad total de unidades"><Input type="number" min="1" step="1" value={preview.quantity} onChange={(e) => setPreview({ ...preview, quantity: Number(e.target.value) })} /></Field><Field label="Departamento"><Select value={preview.department} onValueChange={(value) => value && setPreview({ ...preview, department: value })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{DEPARTAMENTOS.map((department) => <SelectItem key={department} value={department}>{department}</SelectItem>)}</SelectContent></Select></Field><Field label="Método"><Select value={preview.method} onValueChange={(value) => value && setPreview({ ...preview, method: value as ShippingMethodId })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="standard">Estándar</SelectItem><SelectItem value="express">Express</SelectItem></SelectContent></Select></Field><div className={`rounded-xl p-4 ${quote.free ? "bg-emerald-50 text-emerald-900" : "bg-sky-50 text-sky-950"}`}><div className="flex items-center justify-between"><span className="text-sm font-medium">Costo calculado</span><b className="text-2xl">{quote.free ? "Gratis" : formatCOP(quote.cost)}</b></div><p className="mt-2 text-xs">{quote.zone?.name ?? "Tarifa base"} · Entrega estimada entre {quote.method.minDays} y {quote.method.maxDays} días hábiles.</p></div><div className="rounded-xl border p-4 text-sm"><p className="font-semibold">Progreso del beneficio</p>{progress.qualified ? <p className="mt-2 flex items-center gap-2 text-emerald-700"><CheckCircle2 className="h-4 w-4" />Ya cumple las condiciones de envío gratis.</p> : <ul className="mt-2 space-y-1 text-muted-foreground">{settings.freeShipping.byAmount && <li>• Faltan {formatCOP(progress.amountRemaining)} por valor.</li>}{settings.freeShipping.byQuantity && <li>• Faltan {progress.quantityRemaining} unidades.</li>}</ul>}</div></CardContent></Card></aside>
    </div>
  </div>
}

function freeRuleSummary(settings: ShippingSettings) { const rule = settings.freeShipping; if (!rule.enabled) return "Desactivado"; if (rule.byAmount && rule.byQuantity) return rule.mode === "any" ? "Valor o unidades" : "Valor y unidades"; if (rule.byAmount) return `Desde ${formatCOP(rule.minimumAmount)}`; if (rule.byQuantity) return `Desde ${rule.minimumQuantity} und.`; return "Sin condición" }
function Summary({ icon: Icon, label, value, tone }: { icon: typeof Truck; label: string; value: string; tone: "emerald" | "sky" | "violet" | "amber" }) { const styles = { emerald: "bg-emerald-50 text-emerald-700", sky: "bg-sky-50 text-sky-700", violet: "bg-violet-50 text-violet-700", amber: "bg-amber-50 text-amber-700" }; return <Card><CardContent className="flex items-start justify-between p-4"><div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-bold">{value}</p></div><span className={`rounded-xl p-2.5 ${styles[tone]}`}><Icon className="h-5 w-5" /></span></CardContent></Card> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-1.5"><Label>{label}</Label>{children}</div> }
function Toggle({ checked, onChange, label }: { checked: boolean; onChange: (checked: boolean) => void; label: string }) { return <label className="flex cursor-pointer items-center gap-2 text-sm"><input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} className="h-4 w-4 accent-[var(--accent)]" /><span>{label}</span></label> }
function RuleCard({ checked, onChecked, title, description, children }: { checked: boolean; onChecked: (checked: boolean) => void; title: string; description: string; children: React.ReactNode }) { return <div className={`rounded-xl border p-4 ${checked ? "border-accent/40 bg-accent/5" : "opacity-60"}`}><Toggle checked={checked} onChange={onChecked} label={title} /><p className="mb-3 mt-1 text-xs text-muted-foreground">{description}</p>{children}</div> }
function MethodCard({ title, settings, update }: { title: string; settings: ShippingSettings[ShippingMethodId]; update: (patch: Partial<ShippingSettings[ShippingMethodId]>) => void }) { return <div className={`rounded-xl border p-4 ${settings.active ? "" : "opacity-60"}`}><div className="mb-4 flex items-center justify-between"><p className="font-semibold">{title}</p><Toggle checked={settings.active} onChange={(active) => update({ active })} label={settings.active ? "Activo" : "Inactivo"} /></div><div className="grid grid-cols-2 gap-3"><div className="col-span-2"><Field label="Costo base"><Input type="number" min="0" step="1000" value={settings.baseCost} onChange={(e) => update({ baseCost: Number(e.target.value) })} /></Field></div><Field label="Días desde"><Input type="number" min="0" value={settings.minDays} onChange={(e) => update({ minDays: Number(e.target.value) })} /></Field><Field label="Días hasta"><Input type="number" min="0" value={settings.maxDays} onChange={(e) => update({ maxDays: Number(e.target.value) })} /></Field></div><div className="mt-4"><Toggle checked={settings.freeShippingEligible} onChange={(freeShippingEligible) => update({ freeShippingEligible })} label="Aplica para envío gratis" /></div></div> }
